"""initial omnilead schema

Revision ID: 4395dff0b158
Revises:
Create Date: 2026-08-19 12:51:35.963646
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = '4395dff0b158'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.Column('default_currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('demo_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('customers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('primary_phone', sa.String(length=30), nullable=True),
    sa.Column('primary_email', sa.String(length=320), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('customer_type', sa.String(length=30), nullable=True),
    sa.Column('notes_summary', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_customers_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_archived_at'), 'customers', ['archived_at'], unique=False)
    op.create_index(op.f('ix_customers_last_seen_at'), 'customers', ['last_seen_at'], unique=False)
    op.create_index('ix_customers_organization_email', 'customers', ['organization_id', 'primary_email'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_index('ix_customers_organization_last_seen', 'customers', ['organization_id', 'last_seen_at'], unique=False)
    op.create_index('ix_customers_organization_phone', 'customers', ['organization_id', 'primary_phone'], unique=False)
    op.create_table('integrations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'DISCONNECTED'"), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_integrations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    op.create_index(op.f('ix_integrations_is_active'), 'integrations', ['is_active'], unique=False)
    op.create_index('ix_integrations_org_provider_status', 'integrations', ['organization_id', 'provider', 'status'], unique=False)
    op.create_index(op.f('ix_integrations_organization_id'), 'integrations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    op.create_index('uq_integrations_org_provider_external_account', 'integrations', ['organization_id', 'provider', 'external_account_id'], unique=True, postgresql_where=sa.text('external_account_id IS NOT NULL'))
    op.create_table('lead_statuses',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_won', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_lost', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_lead_statuses_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_statuses')),
    sa.UniqueConstraint('organization_id', 'key', name='uq_lead_statuses_organization_key')
    )
    op.create_index(op.f('ix_lead_statuses_is_active'), 'lead_statuses', ['is_active'], unique=False)
    op.create_index('ix_lead_statuses_org_display_order', 'lead_statuses', ['organization_id', 'display_order'], unique=False)
    op.create_index(op.f('ix_lead_statuses_organization_id'), 'lead_statuses', ['organization_id'], unique=False)
    op.create_table('products',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_products_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_products_organization_code')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index('ix_products_organization_name', 'products', ['organization_id', 'name'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=30), server_default=sa.text("'SALES'"), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index('ix_users_organization_email', 'users', ['organization_id', 'email'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_history', 'audit_logs', ['organization_id', 'entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('customer_identities',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('identity_type', sa.String(length=30), nullable=False),
    sa.Column('identity_value', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=False),
    sa.Column('display_value', sa.String(length=500), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_identities_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_customer_identities_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_identities')),
    sa.UniqueConstraint('organization_id', 'identity_type', 'normalized_value', name='uq_customer_identities_org_type_normalized')
    )
    op.create_index(op.f('ix_customer_identities_customer_id'), 'customer_identities', ['customer_id'], unique=False)
    op.create_index('ix_customer_identities_customer_type', 'customer_identities', ['customer_id', 'identity_type'], unique=False)
    op.create_index(op.f('ix_customer_identities_organization_id'), 'customer_identities', ['organization_id'], unique=False)
    op.create_table('duplicate_candidates',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('candidate_customer_id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_customer_id'], ['customers.id'], name=op.f('fk_duplicate_candidates_candidate_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_duplicate_candidates_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_duplicate_candidates_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_duplicate_candidates_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_candidates'))
    )
    op.create_index(op.f('ix_duplicate_candidates_candidate_customer_id'), 'duplicate_candidates', ['candidate_customer_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_created_at'), 'duplicate_candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_customer_id'), 'duplicate_candidates', ['customer_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_match_type'), 'duplicate_candidates', ['match_type'], unique=False)
    op.create_index('ix_duplicate_candidates_org_status_score', 'duplicate_candidates', ['organization_id', 'status', 'match_score'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_organization_id'), 'duplicate_candidates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_status'), 'duplicate_candidates', ['status'], unique=False)
    op.create_index('uq_duplicate_candidates_customer_pair', 'duplicate_candidates', ['organization_id', 'customer_id', 'candidate_customer_id'], unique=True)
    op.create_table('enquiries',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('original_source', sa.String(length=30), nullable=True),
    sa.Column('external_reference_id', sa.String(length=255), nullable=True),
    sa.Column('customer_name_raw', sa.String(length=150), nullable=True),
    sa.Column('contact_raw', sa.String(length=320), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'NEW'"), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('ad_id', sa.String(length=255), nullable=True),
    sa.Column('ad_name', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='fk_enquiries_conversation_id_conversations', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_enquiries_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name='fk_enquiries_interaction_id_interactions', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_enquiries_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enquiries'))
    )
    op.create_index(op.f('ix_enquiries_conversation_id'), 'enquiries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_enquiries_customer_id'), 'enquiries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_enquiries_interaction_id'), 'enquiries', ['interaction_id'], unique=False)
    op.create_index('ix_enquiries_org_source_received', 'enquiries', ['organization_id', 'source', 'received_at'], unique=False)
    op.create_index('ix_enquiries_org_status_received', 'enquiries', ['organization_id', 'status', 'received_at'], unique=False)
    op.create_index(op.f('ix_enquiries_organization_id'), 'enquiries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_enquiries_original_source'), 'enquiries', ['original_source'], unique=False)
    op.create_index(op.f('ix_enquiries_received_at'), 'enquiries', ['received_at'], unique=False)
    op.create_index(op.f('ix_enquiries_source'), 'enquiries', ['source'], unique=False)
    op.create_index(op.f('ix_enquiries_status'), 'enquiries', ['status'], unique=False)
    op.create_index('uq_enquiries_org_source_external_reference', 'enquiries', ['organization_id', 'source', 'external_reference_id'], unique=True, postgresql_where=sa.text('external_reference_id IS NOT NULL'))
    op.create_table('webhook_events',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'RECEIVED'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_webhook_events_integration_id_integrations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_webhook_events_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_integration_id'), 'webhook_events', ['integration_id'], unique=False)
    op.create_index('ix_webhook_events_org_status_received', 'webhook_events', ['organization_id', 'status', 'received_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_organization_id'), 'webhook_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_payload_hash'), 'webhook_events', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_index('ix_webhook_events_provider_payload_hash', 'webhook_events', ['provider', 'payload_hash'], unique=False)
    op.create_index(op.f('ix_webhook_events_received_at'), 'webhook_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.create_index('uq_webhook_events_provider_external_event', 'webhook_events', ['provider', 'external_event_id'], unique=True, postgresql_where=sa.text('external_event_id IS NOT NULL'))
    op.create_table('leads',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('source_enquiry_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('original_source', sa.String(length=30), nullable=True),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('ad_id', sa.String(length=255), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('original_enquiry', sa.Text(), nullable=True),
    sa.Column('purchase_intent', sa.String(length=30), nullable=True),
    sa.Column('lead_score', sa.SmallInteger(), nullable=True),
    sa.Column('priority_score', sa.SmallInteger(), nullable=True),
    sa.Column('followup_risk_score', sa.SmallInteger(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('qualification_summary', sa.Text(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('next_best_action', sa.String(length=50), nullable=True),
    sa.Column('next_best_action_reason', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('followup_risk_score IS NULL OR (followup_risk_score >= 0 AND followup_risk_score <= 100)', name=op.f('ck_leads_followup_risk_score_range')),
    sa.CheckConstraint('lead_score IS NULL OR (lead_score >= 0 AND lead_score <= 100)', name=op.f('ck_leads_lead_score_range')),
    sa.CheckConstraint('priority_score IS NULL OR (priority_score >= 0 AND priority_score <= 100)', name=op.f('ck_leads_priority_score_range')),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], name=op.f('fk_leads_assigned_to_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_leads_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leads_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_leads_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_enquiry_id'], ['enquiries.id'], name=op.f('fk_leads_source_enquiry_id_enquiries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['lead_statuses.id'], name=op.f('fk_leads_status_id_lead_statuses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_archived_at'), 'leads', ['archived_at'], unique=False)
    op.create_index(op.f('ix_leads_assigned_to_user_id'), 'leads', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_leads_followup_risk_score'), 'leads', ['followup_risk_score'], unique=False)
    op.create_index(op.f('ix_leads_last_contact_at'), 'leads', ['last_contact_at'], unique=False)
    op.create_index(op.f('ix_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('ix_leads_next_followup_at'), 'leads', ['next_followup_at'], unique=False)
    op.create_index('ix_leads_org_assignee', 'leads', ['organization_id', 'assigned_to_user_id'], unique=False)
    op.create_index('ix_leads_org_next_followup', 'leads', ['organization_id', 'next_followup_at'], unique=False)
    op.create_index('ix_leads_org_priority', 'leads', ['organization_id', 'priority_score'], unique=False)
    op.create_index('ix_leads_org_status', 'leads', ['organization_id', 'status_id'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_leads_original_source'), 'leads', ['original_source'], unique=False)
    op.create_index(op.f('ix_leads_priority_score'), 'leads', ['priority_score'], unique=False)
    op.create_index(op.f('ix_leads_product_id'), 'leads', ['product_id'], unique=False)
    op.create_index(op.f('ix_leads_purchase_intent'), 'leads', ['purchase_intent'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_source_enquiry_id'), 'leads', ['source_enquiry_id'], unique=False)
    op.create_index(op.f('ix_leads_status_id'), 'leads', ['status_id'], unique=False)
    op.create_table('conversations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('external_conversation_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_conversations_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_conversations_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversations_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_channel'), 'conversations', ['channel'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_lead_id'), 'conversations', ['lead_id'], unique=False)
    op.create_index('ix_conversations_org_customer_channel', 'conversations', ['organization_id', 'customer_id', 'channel'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversations_started_at'), 'conversations', ['started_at'], unique=False)
    op.create_index('uq_conversations_org_channel_external', 'conversations', ['organization_id', 'channel', 'external_conversation_id'], unique=True, postgresql_where=sa.text('external_conversation_id IS NOT NULL'))
    op.create_table('followups',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('followup_type', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'SCHEDULED'"), nullable=False),
    sa.Column('reminder_minutes_before', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rescheduled_from_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], name=op.f('fk_followups_assigned_to_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_followups_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_followups_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_followups_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_followups_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['followups.id'], name=op.f('fk_followups_rescheduled_from_id_followups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_followups'))
    )
    op.create_index(op.f('ix_followups_assigned_to_user_id'), 'followups', ['assigned_to_user_id'], unique=False)
    op.create_index('ix_followups_assignee_status_scheduled', 'followups', ['assigned_to_user_id', 'status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_followups_customer_id'), 'followups', ['customer_id'], unique=False)
    op.create_index(op.f('ix_followups_followup_type'), 'followups', ['followup_type'], unique=False)
    op.create_index(op.f('ix_followups_lead_id'), 'followups', ['lead_id'], unique=False)
    op.create_index('ix_followups_org_status_scheduled', 'followups', ['organization_id', 'status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_followups_organization_id'), 'followups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_followups_scheduled_at'), 'followups', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_followups_status'), 'followups', ['status'], unique=False)
    op.create_table('lead_assignments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('assigned_from_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_lead_assignments_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_from_id'], ['users.id'], name=op.f('fk_lead_assignments_assigned_from_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_lead_assignments_assigned_to_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_assignments_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_lead_assignments_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_assignments'))
    )
    op.create_index(op.f('ix_lead_assignments_assigned_at'), 'lead_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_lead_assignments_assigned_to_id'), 'lead_assignments', ['assigned_to_id'], unique=False)
    op.create_index('ix_lead_assignments_lead_assigned_at', 'lead_assignments', ['lead_id', 'assigned_at'], unique=False)
    op.create_index(op.f('ix_lead_assignments_lead_id'), 'lead_assignments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_assignments_organization_id'), 'lead_assignments', ['organization_id'], unique=False)
    op.create_table('notes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_notes_author_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_notes_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_notes_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notes_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_author_user_id'), 'notes', ['author_user_id'], unique=False)
    op.create_index('ix_notes_customer_created', 'notes', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notes_customer_id'), 'notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notes_is_pinned'), 'notes', ['is_pinned'], unique=False)
    op.create_index('ix_notes_lead_created', 'notes', ['lead_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notes_lead_id'), 'notes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_notes_organization_id'), 'notes', ['organization_id'], unique=False)
    op.create_table('call_recordings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcription_status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_language', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_call_recordings_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_call_recordings_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_call_recordings_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_call_recordings_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_call_recordings_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_recordings')),
    sa.UniqueConstraint('storage_path', name=op.f('uq_call_recordings_storage_path'))
    )
    op.create_index(op.f('ix_call_recordings_conversation_id'), 'call_recordings', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_call_recordings_customer_id'), 'call_recordings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_call_recordings_lead_id'), 'call_recordings', ['lead_id'], unique=False)
    op.create_index('ix_call_recordings_org_status_uploaded', 'call_recordings', ['organization_id', 'transcription_status', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_call_recordings_organization_id'), 'call_recordings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_call_recordings_transcription_status'), 'call_recordings', ['transcription_status'], unique=False)
    op.create_index(op.f('ix_call_recordings_uploaded_at'), 'call_recordings', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_call_recordings_uploaded_by_user_id'), 'call_recordings', ['uploaded_by_user_id'], unique=False)
    op.create_table('interactions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding', VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=150), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_interactions_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_interactions_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_interactions_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_interactions_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_interactions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions'))
    )
    op.create_index(op.f('ix_interactions_actor_user_id'), 'interactions', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_interactions_channel'), 'interactions', ['channel'], unique=False)
    op.create_index(op.f('ix_interactions_conversation_id'), 'interactions', ['conversation_id'], unique=False)
    op.create_index('ix_interactions_conversation_occurred', 'interactions', ['conversation_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_interactions_customer_id'), 'interactions', ['customer_id'], unique=False)
    op.create_index('ix_interactions_customer_occurred', 'interactions', ['customer_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_interactions_direction'), 'interactions', ['direction'], unique=False)
    op.create_index(op.f('ix_interactions_interaction_type'), 'interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_interactions_lead_id'), 'interactions', ['lead_id'], unique=False)
    op.create_index('ix_interactions_lead_occurred', 'interactions', ['lead_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_interactions_occurred_at'), 'interactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_interactions_organization_id'), 'interactions', ['organization_id'], unique=False)
    op.create_index('uq_interactions_org_channel_external_message', 'interactions', ['organization_id', 'channel', 'external_message_id'], unique=True, postgresql_where=sa.text('external_message_id IS NOT NULL'))
    op.create_table('notifications',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('followup_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['followup_id'], ['followups.id'], name=op.f('fk_notifications_followup_id_followups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_notifications_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notifications_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_followup_id'), 'notifications', ['followup_id'], unique=False)
    op.create_index(op.f('ix_notifications_lead_id'), 'notifications', ['lead_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index('ix_notifications_pending_schedule', 'notifications', ['status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_for'), 'notifications', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_status_created', 'notifications', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('enquiry_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('call_recording_id', sa.UUID(), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['call_recording_id'], ['call_recordings.id'], name=op.f('fk_ai_analyses_call_recording_id_call_recordings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_ai_analyses_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_ai_analyses_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], name=op.f('fk_ai_analyses_enquiry_id_enquiries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_ai_analyses_interaction_id_interactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_ai_analyses_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_analyses_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    op.create_index(op.f('ix_ai_analyses_analysis_type'), 'ai_analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_ai_analyses_call_recording_id'), 'ai_analyses', ['call_recording_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_conversation_id'), 'ai_analyses', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_created_at'), 'ai_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analyses_customer_id'), 'ai_analyses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_enquiry_id'), 'ai_analyses', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_input_hash'), 'ai_analyses', ['input_hash'], unique=False)
    op.create_index(op.f('ix_ai_analyses_interaction_id'), 'ai_analyses', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_lead_id'), 'ai_analyses', ['lead_id'], unique=False)
    op.create_index('ix_ai_analyses_lead_type_created', 'ai_analyses', ['lead_id', 'analysis_type', 'created_at'], unique=False)
    op.create_index('ix_ai_analyses_org_type_created', 'ai_analyses', ['organization_id', 'analysis_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_analyses_organization_id'), 'ai_analyses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_status'), 'ai_analyses', ['status'], unique=False)
    op.create_table('objections',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('objection_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_by_ai', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confirmed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DETECTED'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], name=op.f('fk_objections_confirmed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_objections_interaction_id_interactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_objections_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_objections_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objections'))
    )
    op.create_index(op.f('ix_objections_detected_by_ai'), 'objections', ['detected_by_ai'], unique=False)
    op.create_index(op.f('ix_objections_interaction_id'), 'objections', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_objections_lead_id'), 'objections', ['lead_id'], unique=False)
    op.create_index(op.f('ix_objections_objection_type'), 'objections', ['objection_type'], unique=False)
    op.create_index('ix_objections_org_type_status', 'objections', ['organization_id', 'objection_type', 'status'], unique=False)
    op.create_index(op.f('ix_objections_organization_id'), 'objections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_objections_status'), 'objections', ['status'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ai_analysis_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('original_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ai_analysis_id'], ['ai_analyses.id'], name=op.f('fk_ai_feedback_ai_analysis_id_ai_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_feedback_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_ai_feedback_reviewed_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback'))
    )
    op.create_index(op.f('ix_ai_feedback_ai_analysis_id'), 'ai_feedback', ['ai_analysis_id'], unique=False)
    op.create_index('ix_ai_feedback_analysis_reviewed', 'ai_feedback', ['ai_analysis_id', 'reviewed_at'], unique=False)
    op.create_index(op.f('ix_ai_feedback_decision'), 'ai_feedback', ['decision'], unique=False)
    op.create_index(op.f('ix_ai_feedback_organization_id'), 'ai_feedback', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_reviewed_at'), 'ai_feedback', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_ai_feedback_reviewed_by_user_id'), 'ai_feedback', ['reviewed_by_user_id'], unique=False)
    # Deferred cyclic foreign keys.
    # These are added after all participating tables exist.
    op.create_foreign_key(
        "fk_enquiries_conversation_id_conversations",
        "enquiries",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_enquiries_interaction_id_interactions",
        "enquiries",
        "interactions",
        ["interaction_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_enquiries_interaction_id_interactions",
        "enquiries",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_enquiries_conversation_id_conversations",
        "enquiries",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_ai_feedback_reviewed_by_user_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_reviewed_at'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_organization_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_decision'), table_name='ai_feedback')
    op.drop_index('ix_ai_feedback_analysis_reviewed', table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_ai_analysis_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_objections_status'), table_name='objections')
    op.drop_index(op.f('ix_objections_organization_id'), table_name='objections')
    op.drop_index('ix_objections_org_type_status', table_name='objections')
    op.drop_index(op.f('ix_objections_objection_type'), table_name='objections')
    op.drop_index(op.f('ix_objections_lead_id'), table_name='objections')
    op.drop_index(op.f('ix_objections_interaction_id'), table_name='objections')
    op.drop_index(op.f('ix_objections_detected_by_ai'), table_name='objections')
    op.drop_table('objections')
    op.drop_index(op.f('ix_ai_analyses_status'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_organization_id'), table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_org_type_created', table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_lead_type_created', table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_lead_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_interaction_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_input_hash'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_enquiry_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_customer_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_created_at'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_conversation_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_call_recording_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_type'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index('ix_notifications_user_status_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_for'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index('ix_notifications_pending_schedule', table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_lead_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_followup_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_interactions_org_channel_external_message', table_name='interactions', postgresql_where=sa.text('external_message_id IS NOT NULL'))
    op.drop_index(op.f('ix_interactions_organization_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_occurred_at'), table_name='interactions')
    op.drop_index('ix_interactions_lead_occurred', table_name='interactions')
    op.drop_index(op.f('ix_interactions_lead_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_interaction_type'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_direction'), table_name='interactions')
    op.drop_index('ix_interactions_customer_occurred', table_name='interactions')
    op.drop_index(op.f('ix_interactions_customer_id'), table_name='interactions')
    op.drop_index('ix_interactions_conversation_occurred', table_name='interactions')
    op.drop_index(op.f('ix_interactions_conversation_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_channel'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_actor_user_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_call_recordings_uploaded_by_user_id'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_uploaded_at'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_transcription_status'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_organization_id'), table_name='call_recordings')
    op.drop_index('ix_call_recordings_org_status_uploaded', table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_lead_id'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_customer_id'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_conversation_id'), table_name='call_recordings')
    op.drop_table('call_recordings')
    op.drop_index(op.f('ix_notes_organization_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_lead_id'), table_name='notes')
    op.drop_index('ix_notes_lead_created', table_name='notes')
    op.drop_index(op.f('ix_notes_is_pinned'), table_name='notes')
    op.drop_index(op.f('ix_notes_customer_id'), table_name='notes')
    op.drop_index('ix_notes_customer_created', table_name='notes')
    op.drop_index(op.f('ix_notes_author_user_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_lead_assignments_organization_id'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_lead_id'), table_name='lead_assignments')
    op.drop_index('ix_lead_assignments_lead_assigned_at', table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_assigned_to_id'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_assigned_at'), table_name='lead_assignments')
    op.drop_table('lead_assignments')
    op.drop_index(op.f('ix_followups_status'), table_name='followups')
    op.drop_index(op.f('ix_followups_scheduled_at'), table_name='followups')
    op.drop_index(op.f('ix_followups_organization_id'), table_name='followups')
    op.drop_index('ix_followups_org_status_scheduled', table_name='followups')
    op.drop_index(op.f('ix_followups_lead_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_followup_type'), table_name='followups')
    op.drop_index(op.f('ix_followups_customer_id'), table_name='followups')
    op.drop_index('ix_followups_assignee_status_scheduled', table_name='followups')
    op.drop_index(op.f('ix_followups_assigned_to_user_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index('uq_conversations_org_channel_external', table_name='conversations', postgresql_where=sa.text('external_conversation_id IS NOT NULL'))
    op.drop_index(op.f('ix_conversations_started_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index('ix_conversations_org_customer_channel', table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_leads_status_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_source_enquiry_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_purchase_intent'), table_name='leads')
    op.drop_index(op.f('ix_leads_product_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_priority_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_original_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index('ix_leads_org_status', table_name='leads')
    op.drop_index('ix_leads_org_priority', table_name='leads')
    op.drop_index('ix_leads_org_next_followup', table_name='leads')
    op.drop_index('ix_leads_org_assignee', table_name='leads')
    op.drop_index(op.f('ix_leads_next_followup_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_last_contact_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_followup_risk_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_archived_at'), table_name='leads')
    op.drop_table('leads')
    op.drop_index('uq_webhook_events_provider_external_event', table_name='webhook_events', postgresql_where=sa.text('external_event_id IS NOT NULL'))
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_received_at'), table_name='webhook_events')
    op.drop_index('ix_webhook_events_provider_payload_hash', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_payload_hash'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_organization_id'), table_name='webhook_events')
    op.drop_index('ix_webhook_events_org_status_received', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_integration_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('uq_enquiries_org_source_external_reference', table_name='enquiries', postgresql_where=sa.text('external_reference_id IS NOT NULL'))
    op.drop_index(op.f('ix_enquiries_status'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_source'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_received_at'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_original_source'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_organization_id'), table_name='enquiries')
    op.drop_index('ix_enquiries_org_status_received', table_name='enquiries')
    op.drop_index('ix_enquiries_org_source_received', table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_interaction_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_customer_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_conversation_id'), table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_index('uq_duplicate_candidates_customer_pair', table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_status'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_organization_id'), table_name='duplicate_candidates')
    op.drop_index('ix_duplicate_candidates_org_status_score', table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_match_type'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_customer_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_created_at'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_candidate_customer_id'), table_name='duplicate_candidates')
    op.drop_table('duplicate_candidates')
    op.drop_index(op.f('ix_customer_identities_organization_id'), table_name='customer_identities')
    op.drop_index('ix_customer_identities_customer_type', table_name='customer_identities')
    op.drop_index(op.f('ix_customer_identities_customer_id'), table_name='customer_identities')
    op.drop_table('customer_identities')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_history', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index('ix_users_organization_email', table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_organization_name', table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_lead_statuses_organization_id'), table_name='lead_statuses')
    op.drop_index('ix_lead_statuses_org_display_order', table_name='lead_statuses')
    op.drop_index(op.f('ix_lead_statuses_is_active'), table_name='lead_statuses')
    op.drop_table('lead_statuses')
    op.drop_index('uq_integrations_org_provider_external_account', table_name='integrations', postgresql_where=sa.text('external_account_id IS NOT NULL'))
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_organization_id'), table_name='integrations')
    op.drop_index('ix_integrations_org_provider_status', table_name='integrations')
    op.drop_index(op.f('ix_integrations_is_active'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index('ix_customers_organization_phone', table_name='customers')
    op.drop_index('ix_customers_organization_last_seen', table_name='customers')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index('ix_customers_organization_email', table_name='customers')
    op.drop_index(op.f('ix_customers_last_seen_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_archived_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
